### ISSUE TITLE
abi checker is stuck on Focal and Groovy

### ISSUE THREAD

**Issue by ahcorde** [osrf/auto-abi-checker#24]
The build is stuck in the ABI checker http://build.ros2.org/job/Fpr__rmw_implementation__ubuntu_focal_amd64/12/console. Returning timeouts http://build.ros2.org/job/Fpr__rmw_implementation__ubuntu_focal_amd64/10/

There is no message about what could be happening. Any thoughts ?

**Comment by j-rivero** [comment]
can you reproduce it locally?

**Comment by ahcorde** [comment]
yes, locally is stuck too

**Comment by ahcorde** [comment]
rmw_implementation does not have any header file. I don't know if this may affect.

**Comment by j-rivero** [comment]
> rmw_implementation does not have any header file. I don't know if this may affect.

That could be the reason indeed. Could please check version of the abi-compliance-checker? it could be related to https://github.com/ros-infrastructure/ros_buildfarm/pull/817

**Comment by ahcorde** [comment]
Yes, this PR fix the issue at least locally

**Comment by j-rivero** [comment]
nothing more we can do in this repo
